openapi: 3.0.0
info:
  description: Alert for API Manager
  title: Alert API Manager
  version: 1.0.0
servers:
- description: Anypoint Cloudhub
  url: https://anypoint.mulesoft.com/apimanager/api/
- description: Anypoint Cloudhub EU
  url: https://eu1.anypoint.mulesoft.com/apimanager/api/
security:
- bearerAuth: []
paths:
  /v1/organizations/{orgId}/environments/{envId}/apis/{apiVersion}/alerts:
    get:
      description: Get Alerts from API manager
      parameters:
      - description: The organization Id
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: The environment id
        explode: false
        in: path
        name: envId
        required: true
        schema:
          type: string
        style: simple
      - description: The api version
        explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/AlertWithId'
                title: alerts from GET
                type: array
          description: Success response
      summary: GetAlertsfromAPImanager
    post:
      description: Create a new alert for API manager
      operationId: CreateAlertForAPIManagerInstance
      parameters:
      - description: The organization Id
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: The environment id
        explode: false
        in: path
        name: envId
        required: true
        schema:
          type: string
        style: simple
      - description: The api version
        explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alert'
      responses:
        "401":
          description: Access token is missing or invalid
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertWithId'
          description: Success create an alert
  /v1/organizations/{orgId}/environments/{envId}/apis/{apiVersion}/alerts/{cloudhubApimAlert}:
    delete:
      description: Delete an Alert from API manager
      operationId: DeleteanAlertfromAPImanager
      parameters:
      - description: The organization Id
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: the environment id
        explode: false
        in: path
        name: envId
        required: true
        schema:
          type: string
        style: simple
      - description: the api version
        explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      - description: the id of the alert
        explode: false
        in: path
        name: cloudhubApimAlert
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "204":
          content:
            text/plain:
              example: successfully deleted
          description: No content
      summary: DeleteanAlertfromAPImanager
    get:
      description: Get one alert
      operationId: Getonealert
      parameters:
      - description: The organization Id
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: the environment id
        explode: false
        in: path
        name: envId
        required: true
        schema:
          type: string
        style: simple
      - description: the api version
        explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      - description: the id of the alert
        explode: false
        in: path
        name: cloudhubApimAlert
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertWithId'
          description: Success response
      summary: Getonealert
    patch:
      description: Modify one alert from API manger
      operationId: ModifyonealertfromAPImanger
      parameters:
      - description: The organization Id
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: the environment id
        explode: false
        in: path
        name: envId
        required: true
        schema:
          type: string
        style: simple
      - description: the api version
        explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      - description: the id of the alert
        explode: false
        in: path
        name: cloudhubApimAlert
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertWithId'
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertWithId'
          description: Success response
      summary: ModifyonealertfromAPImanger
components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    BadRequestError:
      content:
        application/json:
          schema:
            properties:
              status:
                default: 400
                title: the response status code
                type: integer
              message:
                example: api error message
                title: the error message
                type: string
            type: object
      description: Bad request response
    SuccessGetAlerts:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/AlertWithId'
            title: alerts from GET
            type: array
      description: Success response
    SuccessGetAlert:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AlertWithId'
      description: Success response
    SuccessCreateAlert:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AlertWithId'
      description: Success create an alert
  schemas:
    Alert:
      example:
        apiAlertsVersion: apiAlertsVersion
        severity: severity
        condition:
          value: 0
          operator: operator
          resourceType: resourceType
          aggregate: aggregate
        period:
          duration:
            count: 6
            weight: weight
          repeat: 1
        recipients:
        - firstName: firstName
          lastName: lastName
          type: type
          value: value
        - firstName: firstName
          lastName: lastName
          type: type
          value: value
        name: name
        type: type
        enabled: true
      properties:
        apiAlertsVersion:
          type: string
        name:
          type: string
        type:
          type: string
        enabled:
          type: boolean
        severity:
          type: string
        recipients:
          items:
            $ref: '#/components/schemas/Recipient'
          type: array
        condition:
          $ref: '#/components/schemas/Condition'
        period:
          $ref: '#/components/schemas/Period'
      required:
      - apiAlertsVersion
      - condition
      - enabled
      - name
      - period
      - recipients
      - severity
      - type
      title: Alert
      type: object
    Recipient:
      example:
        firstName: firstName
        lastName: lastName
        type: type
        value: value
      properties:
        type:
          type: string
        value:
          type: string
        firstName:
          type: string
        lastName:
          type: string
      required:
      - firstName
      - lastName
      - type
      - value
      title: recipient
      type: object
    Condition:
      example:
        value: 0
        operator: operator
        resourceType: resourceType
        aggregate: aggregate
      properties:
        resourceType:
          type: string
        aggregate:
          type: string
        operator:
          type: string
        value:
          format: int32
          type: integer
      required:
      - aggregate
      - operator
      - resourceType
      - value
      title: condition
      type: object
    Period:
      example:
        duration:
          count: 6
          weight: weight
        repeat: 1
      properties:
        duration:
          $ref: '#/components/schemas/Duration'
        repeat:
          format: int32
          type: integer
      required:
      - duration
      - repeat
      title: period
      type: object
    Duration:
      example:
        count: 6
        weight: weight
      properties:
        count:
          format: int32
          type: integer
        weight:
          type: string
      required:
      - count
      - weight
      title: duration
      type: object
    AlertWithId:
      example:
        apiAlertsVersion: apiAlertsVersion
        severity: severity
        condition:
          value: 0
          operator: operator
          resourceType: resourceType
          aggregate: aggregate
        period:
          duration:
            count: 6
            weight: weight
          repeat: 1
        recipients:
        - firstName: firstName
          lastName: lastName
          type: type
          value: value
        - firstName: firstName
          lastName: lastName
          type: type
          value: value
        name: name
        id: id
        type: type
        enabled: true
      properties:
        apiAlertsVersion:
          type: string
        name:
          type: string
        type:
          type: string
        enabled:
          type: boolean
        severity:
          type: string
        recipients:
          items:
            $ref: '#/components/schemas/Recipient'
          type: array
        condition:
          $ref: '#/components/schemas/Condition'
        period:
          $ref: '#/components/schemas/Period'
        id:
          type: string
      required:
      - apiAlertsVersion
      - condition
      - enabled
      - id
      - name
      - period
      - recipients
      - severity
      - type
      title: AlertWithId
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
